### ISSUE TITLE
how i can parse weblogic log file to logstash in windows

### ISSUE THREAD

**Issue by alqasem** [kelvinfann/scripts#1]
i am using logstash in windows 7 and now i need to parse weblogic log file to logstash
,any help ?
thank you.

**Comment by kelvinfann** [comment]
Uhhh, I am a bit confused about what you want? You want me to write a script to parse web logic log files?

These scripts were just things I wrote to help me test/develop the plugins I am writing for log stash. The only reason they were uploaded was to share them with a few coworkers.

**Comment by alqasem** [comment]
yes , i want script to parse web logic log files.
thank you.

**Comment by kelvinfann** [comment]
@alqasem wait I think you mean you want an input plugin for web logic log files. 

Regardless, what I meant essentially is no, I am probably not going to write a script or input plugin for web logic files. I don't even know what web logic files are? Sorry about that. 

If you want a plugin I suggest you try your hand at writing yourself? https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html

**Comment by alqasem** [comment]
@kelvinfann thank very much , and thank again for your time.
